const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const study = fs.readFileSync(path.join(root, "study-app.js"), "utf8");
const notes = fs.readFileSync(path.join(root, "notes-app.js"), "utf8");
const ai = fs.readFileSync(path.join(root, "ai-app.js"), "utf8");
const speakingApp = fs.readFileSync(path.join(root, "speaking-app.js"), "utf8");
const styles = fs.readFileSync(path.join(root, "styles.css"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");

assert.doesNotMatch(study, /data-tab="settings"[^\n]+setTimeout\(renderSettings/);
assert.doesNotMatch(study, /data-tab="flashcards"[^\n]+setTimeout\(renderReview/);
assert.doesNotMatch(study, /data-tab="dictation"[^\n]+setTimeout\(renderDictation/);
assert.match(index, /data-tab="study"/);
assert.match(index, /id="view-study"/);
assert.match(study, /async function renderStudy/);
assert.match(app, /flashcards:"study"/);
assert.match(study, /coreRefreshPromise/);
assert.match(study, /Date\.now\(\) - state\.coreRefreshedAt < 30_000/);
assert.match(notes, /Date\.now\(\) - state\.refreshedAt < 30_000/);
assert.match(notes, /const notePromise = loadNote\(id\)/);
assert.match(notes, /Promise\.all\(\[\s*api\(`\/api\/notes\/\$\{note\.id\}`/);
assert.match(notes, /schedulePreview/);
assert.match(notes, /ielts_note_view_mode/);
assert.match(notes, /ielts_note_editor_width/);
assert.match(notes, /syncPreviewToMarkdown/);
assert.match(notes, /pastePlainTextIntoPreview/);
assert.match(index, /id="note-preview" contenteditable="true"/);
assert.match(index, /data-note-view="preview"/);
assert.match(styles, /\.chat-list \{[^}]*min-height: 0;[^}]*flex: 1 1 auto;[^}]*overflow-y: auto;/);
assert.match(styles, /\.note-list \{[^}]*min-height: 0;[^}]*overflow-y: auto;/);
assert.match(styles, /\.note-workspace\[data-note-view="preview"\]/);
assert.match(ai, /chatSelectionToken/);
assert.match(ai, /chatCache: new Map\(\)/);
assert.match(ai, /chatHtmlCache: new Map\(\)/);
assert.match(ai, /scheduleMessagesRender/);
assert.match(ai, /正在生成…/);
assert.match(ai, /此回复没有可显示内容，请重新生成。/);
assert.match(ai, /if \(!assistant\.content\.trim\(\)\) throw new Error\("模型没有返回可显示内容，请重试。"\)/);
assert.doesNotMatch(ai, /DELETE" \}\); state\.activeChat = null; await refreshChats\(\)/);
assert.match(study, /limit:"50"/);
assert.match(study, /libraryRequestToken/);
assert.match(app, /behavior: "auto"/);
assert.match(styles, /body\.has-custom-background \.view\.active \{ animation: none; \}/);
assert.match(app, /let suggestionController = null;/);
assert.match(app, /suggestionController\?\.abort\(\);/);
assert.match(app, /AbortSignal\.any\(\[suggestionController\.signal, AbortSignal\.timeout\(2500\)\]\)/);
assert.match(app, /addEventListener\("compositionstart", \(\) => \{\s*searchComposing = true;/);
assert.match(app, /addEventListener\("compositionend", event => \{\s*searchComposing = false;\s*scheduleSuggestions\(event\.target\.value, 0\);/);
assert.match(app, /if \(!searchComposing\) scheduleSuggestions\(event\.target\.value\);/);
assert.match(styles, /\.suggestions \{ display: none; max-height: min\(320px, 42vh\); margin-top: 8px;/);
assert.doesNotMatch(styles, /\.suggestions \{[^}]*position:\s*absolute/);
assert.match(index, /data-tab="speaking"/);
assert.match(index, /id="view-speaking"/);
assert.match(index, /speaking-app\.js/);
assert.match(app, /if \(target === "speaking"\) window\.VocabSpeaking\?\.activate\?\.\(\);/);
assert.match(app, /window\.VocabSpeaking\?\.pause\?\.\(\);/);
assert.match(speakingApp, /\/api\/speaking\/set/);
assert.match(speakingApp, /\/api\/speaking\/feedback/);
assert.match(speakingApp, /webkitSpeechRecognition/);
assert.match(styles, /\.speaking-timer/);
assert.match(styles, /\.speaking-part-grid/);
assert.match(app, /function isDictionaryMatch\(item\) \{ return Boolean\(item\?\.exact \|\| item\?\.match_kind === "inflection" \|\| item\?\.match_kind === "phrase"\); \}/);
assert.match(app, /function chineseTokens/);
assert.match(app, /function dictionaryTimeout/);
assert.match(app, /source === "smart"\) return 20000/);
assert.match(app, /function shouldAutoTranslate/);
assert.match(app, /function looseQuery/);
assert.match(app, /lookupWithAi/);
assert.match(app, /isTimeoutError/);
assert.match(app, /suggestion-query/);
assert.match(styles, /\.suggestion-query b/);
assert.match(app, /replace\(\/\\s\+\/g, " "\)/);
assert.doesNotMatch(index, /dictionary-source-switch/);
assert.doesNotMatch(app, /data-dictionary-source-jump/);
assert.match(app, /Google 翻译/);
assert.doesNotMatch(app, /requestDictionary\(query, "free", signal\)/);
assert.match(styles, /\.inflection-note/);
assert.match(styles, /\.dictionary-language-notice/);

console.log("performance UI guard tests passed");
